- hosts: localhost
  gather_facts: false
  vars_files:
  - "{{ playbook_dir }}/config.yml"
  vars:
    durations: "{{ item }}"
  tasks:
  - name: Download crane
    # get_url downloads every time even if force=no
    # this causes a pretty long delay since the file is
    # somewhat large
    # https://github.com/ansible/ansible/issues/64016
    #
    #get_url:
    #  url: http://people.redhat.com/jmontleo/crane
    #  dest: "{{ crane_path }}"
    #  mode: 0755
    #
    shell: "wget -N -P {{ crane_path }} http://people.redhat.com/jmontleo/crane && chmod 755 {{ crane_path }}/crane"
    args:
      warn: false
    when: download_crane

  - name: Run batched export
    include_tasks: crane-export-batch.yml
    loop: "{{ namespaces | batch(batch_count) | list }}"

  - name: Create transforms
    shell: "{{ crane_path }}/crane transform --from-openshift --export-dir=export/resources"

  - name: Find token transforms
    find:
      path: "{{ playbook_dir }}/transform"
      recurse: true
      patterns: 'transforms-Secret.*token.*yaml'
      use_regex: true
    register: tokens

  - name: Add token label json patch
    copy:
      content: '[{"op":"add","path":"/metadata/labels", "value": {}},{"op":"add","path":"/metadata/labels/exported-by", "value":"crane2"}]'
      dest: "{{ item.path }}"
    with_items: "{{ tokens.files }}"

  - name: Apply Transforms
    shell: "{{ crane_path }}/crane apply --export-dir=export/resources"
