- hosts: localhost
  gather_facts: false
  vars_files:
  - "{{ playbook_dir }}/config.yml"
  vars:
    durations: "{{ item }}"
  tasks:
  - name: Delete unwanted resources
    include_tasks: crane-delete-unwanted-resources.ymll
    with_items: "{{ namespaces }}"

  - name: Run batched import
    include_tasks: crane-import-batch.yml
    loop: "{{ namespaces | batch(batch_count) | list }}"
